metadata:
  namespace: car-registry
spec:
  replicas: ${replicaCount}
  template:
    spec:
      containers:
      - env:
        - name: datatier_service_endpoint
          value: http://carfeatureregistrationdatatier
        - name: SB_QUEUE_CONNECTIONSTRING  
          valueFrom:
            secretKeyRef:
              name: outputqueue-secret
              key: SB_QUEUE_CONNECTIONSTRING
        - name: QUEUE_NAME
          valueFrom:
            secretKeyRef:
              name: outputqueue-secret
              key: QUEUE_NAME
        resources:
          limits:
            cpu: 400m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 300Mi