spec:
  template:
    spec:
      containers:
      - env:
        - name: LOGIC_SERVICE_ENDPOINT
          value: http://carfeatureregistrationbislogictier
        - name: SUBSCRIPTION_NAME
          valueFrom:
            secretKeyRef:
              name: topicsb-secret
              key: SUBSCRIPTION_NAME        
        - name: TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: topicsb-secret
              key: TOPIC_NAME
        - name: SB_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: topicsb-secret
              key: SB_CONNECTIONSTRING